"""adding info

Revision ID: 2283a96b8a2e
Revises: d30b79c83c92
Create Date: 2025-07-02 00:12:29.328110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2283a96b8a2e'
down_revision = 'd30b79c83c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('employment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
