"""empty message

Revision ID: 308a0b69a7ef
Revises: b87544077298
Create Date: 2025-07-16 10:52:17.745077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308a0b69a7ef'
down_revision = 'b87544077298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
