"""empty message

Revision ID: 538731e02158
Revises: 827e97337a44
Create Date: 2025-07-16 13:12:09.933641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538731e02158'
down_revision = '827e97337a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
