"""adding foreign key for relation

Revision ID: 61067d4ed074
Revises: 4571b4dfff0a
Create Date: 2025-07-01 23:21:12.087659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61067d4ed074'
down_revision = '4571b4dfff0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
