"""empty message

Revision ID: 827e97337a44
Revises: 308a0b69a7ef
Create Date: 2025-07-16 11:43:33.359055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827e97337a44'
down_revision = '308a0b69a7ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=1027), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('date')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
