"""adding date and thing

Revision ID: befef4d07f6d
Revises: c66541f2848e
Create Date: 2025-06-16 18:36:13.444451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'befef4d07f6d'
down_revision = 'c66541f2848e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('filepath', sa.String(length=255), nullable=False))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('newsletter', schema=None) as batch_op:
        batch_op.drop_column('filepath')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
