"""more paragraph length

Revision ID: d30b79c83c92
Revises: 61067d4ed074
Create Date: 2025-07-02 00:01:48.600539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd30b79c83c92'
down_revision = '61067d4ed074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=2000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paragraph', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.String(length=2000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
